breeze_api:
  api_token: 3088X_y892P%7c#516`r8i9kx2K485&8
  secret_token: 530zM488$968889l8rD9a7S35(2984w1
  session_id: 52167302
kite_connect:
  access_token: WQI7Jbs2ItkpM8gBOdU86L2cFOHa5hTv
  api_key: ldhfjwk4z3wn9v9d
  api_secret: k8ri5fj6wtn404iqq3bmt5ntdplubua1
  redirect_url: http://localhost:8000/login
  request_token: EPcZBLSMKV1CEFyxggABrE6bHyH4UW8M
stratergy:
  buy: 0.3
  linear_from: 1
  order_count: 10
  price_difference_percent: 0.5
  sell: 0.5
  start_buy: 1
  start_quantity: 1
